### ISSUE TITLE
ml.classify is not a function

### ISSUE THREAD

**Issue by mathildebuenerd** [syzer/sentiment-analyser#28]
Is this package still working?
I can't manage to make it work. On the [RunKit](https://npm.runkit.com/ml-sentiment), the code below gives a `TypeError: mlSentiment.classify is not a function`

```javascript
var mlSentiment = require("ml-sentiment");
let test = mlSentiment.classify(`How are you doing today ? I feel a bit strange I think`);
console.log(test);
```

**Comment by mathildebuenerd** [comment]
Seems I had to initialize the language before using it.

```javascript
const mlSentiment = require("ml-sentiment");
const sentiment = mlSentiment({lang: 'en'}); // added this line
let test = sentiment.classify(`I am so happy!!!!`);
console.log(test);
```

**Comment by mecherguikhaoula** [comment]
i want the language french instead of english ,i put 'fr' in th place of 'en' but it didn't work, have you any idea please ?
